<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJTn4gcc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJTn4gcc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJTn4gcc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJTn4gcc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJTn4gcc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JTn4gcc',
    'container.build_id' => '01b189e5',
    'container.build_time' => 1556206896,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJTn4gcc');
