<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXtWhaZK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXtWhaZK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXtWhaZK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXtWhaZK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXtWhaZK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XtWhaZK',
    'container.build_id' => '945c0128',
    'container.build_time' => 1555678761,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXtWhaZK');
