<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUzdOQF7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUzdOQF7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUzdOQF7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUzdOQF7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUzdOQF7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UzdOQF7',
    'container.build_id' => '79a20bc3',
    'container.build_time' => 1556287778,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUzdOQF7');
